overrides:
  rimraf: 6.1.3
autoInstallPeers: false
peerDependencyRules:
  ignoreMissing:
    - electron-builder-squirrel-windows

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
